version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${root}
      POSTGRES_PASSWORD: ${root}
      POSTGRES_DB: ${db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
        #    healthcheck:
        #      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root}"]
        #   interval: 10s
        #    timeout: 5s
        #      retries: 5   

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${root}
      DB_PASSWORD: ${root}
      DB_NAME: ${db}
      DATABASE_URL: postgresql://root:root@postgres:5432/db
    depends_on:
      - postgres
    ports:
      - "5000:5000" # Adjust this if your backend uses a different port
        #   volumes:
      #   - ./backend:/app
        #    command: ["python", "manage.py", "runserver", "0.0.0.0:5000"] # Adjust according to your backend framework

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_service
      #    environment:
      #      REACT_APP_BACKEND_URL: http://localhost:5000 # Update this for other frameworks
    ports:
      - "3000:3000"
        #    volumes:
      #     - ./frontend:/app
      #  command: ["npm", "start"] # Adjust this based on your frontend framework

volumes:
  postgres_data:

